"""add calendar_event_id to bills

Revision ID: 5cefe8cf8053
Revises: 9fb310515192
Create Date: 2026-04-14 23:36:50.665176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cefe8cf8053'
down_revision: Union[str, Sequence[str], None] = '9fb310515192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_event_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'default', name='calendarprovider'), nullable=False),
    sa.Column('event_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bills', sa.Column('calendar_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'calendar_event_id')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
