"""add calendar_event_id to bills

Revision ID: 5e4fddd0552a
Revises: 5cefe8cf8053
Create Date: 2026-04-14 23:39:15.737499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e4fddd0552a'
down_revision: Union[str, Sequence[str], None] = '5cefe8cf8053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', postgresql.ENUM('google', 'default', name='calendarprovider'), autoincrement=False, nullable=False),
    sa.Column('event_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('calendar_events_pkey'))
    )
    # ### end Alembic commands ###
