"""create bills table

Revision ID: 9fb310515192
Revises: 
Create Date: 2026-04-02 20:53:22.614030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb310515192'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('biller', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'paid', 'overdue', name='billstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('billing_month', sa.Date(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills')
    # ### end Alembic commands ###
